
/* Insert entries into employers table */

INSERT INTO employers (name, about, address, phone, email, pwd) values ('Abafix','Top hospital in rural Victoria ','73 Frouds Road, MALLACOOTA, VIC, 3892','(03) 5303 9945','Abafix@orgmail.com','ab180003');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Albent','Commercial and Institutional Building Construction','77 Chatsworth Drive, BURSWOOD, WA, 6100','(08) 9350 2576','Albent@orgmail.com','al190822');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Antigen','Services for the Elderly and Persons with Disabilities','74 Walters Street, WARRENBAYNE, VIC, 3670','(03) 5378 4638','Antigen@orgmail.com','an508680');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Archend ','Pesticide and Other Agricultural Chemical Manufacturing','68 Ocean Street, MILLERS POINT, NSW, 2000','(02) 8361 3759','Archend @orgmail.com','ar878957');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Bellity','Adhesive Manufacturing','80 Moores Drive, PERTH, WA, 6000','(08) 9268 8559','Bellity@orgmail.com','be537674');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Bovist','Document Preparation Services','46 Point Walter Road, PALMYRA DC, WA, 6157','(08) 9481 3265','Bovist@orgmail.com','bo605984');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Calcicious','Exterminating and Pest Control Services','60 Flax Court, TALGARNO, VIC, 3691','(03) 5359 5444','Calcicious@orgmail.com','ca640059');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Canosis','Fortune 500 casino and gambling chain ','20 Edgecliff Road, ZETLAND, NSW 2017','(02) 9829 6221','Canosis@orgmail.com','ca185032');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Capise ','Security Systems Services','85 Gloucester Avenue, REGENCY PARK BC, SA, 5010','(08) 8381 2395','Capise @orgmail.com','ca976931');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Cedize','Computer Systems Design and Related Services','72 Edward Bennett Drive, PEMULWUY, NSW, 2145','(02) 8830 3931','Cedize@orgmail.com','ce721771');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Centitri','Refrigerated Warehousing and Storage','82 Ocean Street, HAYMARKET, NSW, 2000','(02) 8976 7487','Centitri@orgmail.com','ce930654');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Cervore','Professional Employer Organizations','31 Lewin Street, QUANDARY, NSW, 2665','(02) 6121 5180','Cervore@orgmail.com','ce391991');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Combu','Wired Telecommunications Carriers','35 Girvan Grove, SPECIMEN HILL, VIC, 3555, (03) 5327 0384','(03) 9887 6499','Combu@orgmail.com','co212099');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Contrare','Public Relations Agencies','17 Glendonbrook Road, DUNVILLE LOOP, NSW, 2849','(02) 4038 9209','Contrare@orgmail.com','co548732');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Diamia','Building Inspection Services in regional NSW','86 Oak Street, ACACIA CREEK, NSW, 2476','(02) 6717 3214','Diamia@orgmail.com','di626790');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Difent','Media Buying Agencies','40 Commercial Street, SPRINGFIELD, VIC, 3434','(03) 8008 9453','Difent@orgmail.com','di831272');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Divafy','Display Advertising Services','13 Saggers Road, JERDACUTTUP, WA, 6346','(08) 9014 5692','Divafy@orgmail.com','di686283');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Dizio','Management Consulting Services','95 Frouds Road, COBUNGRA, VIC, 3898','(03) 5352 9849','Dizio@orgmail.com','di390848');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Esosis','Satellite Telecommunications','32 Mt Berryman Road, PINELANDS, QLD, 4355','(07) 4541 3761','Esosis@orgmail.com','es507191');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Exill','Employment Placement Agency','5 Battery Drive, Manuka, ACT, 2603','(02) 6163 4611','Exill@orgmail.com','ex985290');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Favu','Transport services','22 Trelawney Street, CENTENNIAL PARK, NSW, 2021','(02) 9739 1822','Favu@orgmail.com','fa897060');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Gezio','Community Food Services','91 Horsington Street, BURNLEY NORTH, VIC, 3121','(03) 9887 6418','Gezio@orgmail.com','ge651508');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Gradinoodle','Investigation, Guard, and Armored Car Services','54 Thyme Avenue, GLENLYON, QLD, 4380','(07) 4568 4676','Gradinoodle@orgmail.com','gr412293');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Insulible','Telephone Call Centers','21 Decca Road, VIRGINIA, NT, 0835','(08) 8967 1978','Insulible@orgmail.com','in537517');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Kayor','Synthetic Dye and Pigment Manufacturing','36 Parkes Road, MELBOURNE, VIC, 3000','(03) 8122 0714','Kayor@orgmail.com','ka469758');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Kilane','Mortgage and Nonmortgage Loan Brokers','51  Grandis Road, CORANGULA, NSW, 2440','(02) 6787 7693','Kilane@orgmail.com','ki596964');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Laudize','Pesticide and Other Agricultural Chemical Manufacturing','76 Treasure Island Avenue, BURLEIGH BC, QLD, 4220','(07) 5662 4098','Laudize@orgmail.com','la911591');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Lupent','Media Representatives','36 Peninsula Drive, LOFTUS, NSW, 2232','(02) 4244 9674','Lupent@orgmail.com','lu255839');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Manulith','Landscaping Services','59 Pelican Road, CHRISTMAS ISLAND, WA, 6798','(08) 9010 9428','Manulith@orgmail.com','ma660813');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Meelane','Vocational Rehabilitation Services','46 Yangan Drive, GARTHOWEN, NSW, 2345','(02) 6730 2886','Meelane@orgmail.com','me686080');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Midose','Business Service Centers','33 Quayside Vista, CANBERRA, ACT, 2601','(02) 6147 3002','Midose@orgmail.com','mi114408');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Minix','Professional and Management Development Training','62 Jacabina Court, GWYNNEVILLE, NSW, 2500','(02) 4220 4712','Minix@orgmail.com','mi878317');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Mistindu','Veterinary Services','58 Mackie Street, NAROOMA, NSW, 2546','(02) 4074 7032','Mistindu@orgmail.com','mi456999');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Omniveo','Artificial and Synthetic Fibers and Filaments Manufacturing','85 Chatsworth Drive, LATHLAIN, WA, 6100','(08) 9377 9601','Omniveo@orgmail.com','om834009');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Paleombee','Power and Communication Line and Related Structures Construction','29 Pelican Road, GLEBE, TAS, 7000','(03) 6223 7253','Paleombee@orgmail.com','pa280738');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Pixonoodle','Chain of Fitness and Recreational Sports Centers','5 Grandis Road, GEORGES CREEK, NSW, 2440','(02) 6767 2979','Pixonoodle@orgmail.com','pi559385');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Plambu','Iron Ore Mining','65 Girvan Grove, BENDIGO, VIC, 3550','(03) 5311 1165','Plambu@orgmail.com','pl929410');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Polyor','Couriers and Express Delivery Services','87 Tennyson Road, BANKSTOWN, NSW, 2200','(02) 9782 9432','Polyor@orgmail.com','po640351');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Quasita','Pharmaceutical and Medicine Manufacturing','24 Moruya Road, BALLALABA, NSW, 2622','(02) 6192 0013','Quasita@orgmail.com','qu354047');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Retri','Environmental Consulting Services','54 Henry Street, GROVEDALE, VIC, 3216','(03) 5307 8743','Retri@orgmail.com','re917181');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Seminix','Paint and Coating Manufacturing','67 Woodlands Avenue, PARRAMATTA WESTFIELD, NSW, 2150','(02) 9431 3390','Seminix@orgmail.com','se585520');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Superic ','Provides Nondepository Credit Intermediation services','45 Begley Street, ADELAIDE BC, SA, 5000','(08) 8275 7855','Superic @orgmail.com','su133371');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Supoid','Chain of Outdoor Power Equipment Stores','15 Ocean Street, SYDNEY SOUTH, NSW, 2000','(02) 8583 7503','Supoid@orgmail.com','su233646');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Suprambo','Temporary Help Services','77 Watson Street, BARNADOWN, VIC, 3557','(03) 5319 0561','Suprambo@orgmail.com','su263349');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Surose','Fertilizer Manufacturing','45 Seiferts Rd, BARMOYA, QLD, 4703','(07) 4987 1111','Surose@orgmail.com','su635989');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Syore','Promoters of Performing Arts, Sports, and Similar Events with Facilities','63 Oak Street, TULLYMORGAN, NSW, 2463','(02) 6771 8803','Syore@orgmail.com','sy229470');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Tadoo','Medical and Diagnostic Laboratories','77 Ross Smith Avenue, DARWIN, NT, 0800','(08) 8926 8155','Tadoo@orgmail.com','ta319283');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Transore','Top hotel chain in regional NSW','72 Elizabeth Street, Sandy Creek, QLD 4570','(07) 5359 3172','Transore@orgmail.com','tr128589');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Yado','The largest Oil and Gas Extraction firm in the Asia-Pacific','13 McGregor Street, TUGGERANONG, ACT, 2900','(02) 6188 3805','Yado@orgmail.com','ya138741');
INSERT INTO employers (name, about, address, phone, email, pwd) values ('Zootri','Direct Mail Advertising Services','21 Grandis Road, WILLAWARRIN, 2440','(02) 6765 0304','Zootri@orgmail.com','zo903355');



/* Insert entries into jobs table */
INSERT INTO jobs (title, skills) values ('Applications Analyst','Balsamiq, JIRA');
INSERT INTO jobs (title, skills) values ('Applications Programmer','Github, Python');
INSERT INTO jobs (title, skills) values ('Computer Language Coder','Textmate, Sublime Text, JIRA, NetBeans');
INSERT INTO jobs (title, skills) values ('Computer Network Engineer','Wireshark, Nagios, Capsa');
INSERT INTO jobs (title, skills) values ('Computer Programmer','Rubber duck, Sublime Text');
INSERT INTO jobs (title, skills) values ('Computer Systems Analyst','Sublime Text, JIRA, NetBeans');
INSERT INTO jobs (title, skills) values ('Computer Systems Consultant','Textmate, Sublime Text, JIRA');
INSERT INTO jobs (title, skills) values ('Computer Systems Software Architect','AutoCad, SketchUp, ArchiCAD');
INSERT INTO jobs (title, skills) values ('Computer Systems Software Engineer','Eclipse, Visual Studio');
INSERT INTO jobs (title, skills) values ('Data Processing Systems Analyst','Hadoop, Qubole');
INSERT INTO jobs (title, skills) values ('Embedded Systems Software Developer','Eclipse, MATLAB, MPLAB');
INSERT INTO jobs (title, skills) values ('Enterprise Systems Engineer','CAE Simulation, SCCM');
INSERT INTO jobs (title, skills) values ('Information Systems Analyst','BizFluent, Trudera');
INSERT INTO jobs (title, skills) values ('Information Systems Planner','SISP, TDAN');
INSERT INTO jobs (title, skills) values ('Internet Application Developer','Angular.JS., Grunt, jQuery, Grunt');
INSERT INTO jobs (title, skills) values ('Internet Developer','Bootstrap,  jQuery, Atom');
INSERT INTO jobs (title, skills) values ('Intranet Developer','ThoughtFarmer, Beekeeper');
INSERT INTO jobs (title, skills) values ('Junior Software Developer','Textmate, Sublime Text, HTML, CSS, JavaScript');
INSERT INTO jobs (title, skills) values ('Senior Software Developer ','HTML, CSS, JavaScript, Jquery, Node, MONGODB');
INSERT INTO jobs (title, skills) values ('Mainframe Programmer','COBOL, CLIST ');
INSERT INTO jobs (title, skills) values ('Network Designer','eDraw. Visio, ConceptDraw Pro');
INSERT INTO jobs (title, skills) values ('Network Developer','Radar, DevTool');
INSERT INTO jobs (title, skills) values ('Network Engineer','Zabbix, Icinga');
INSERT INTO jobs (title, skills) values ('Programmer Analyst','SQL, Python');
INSERT INTO jobs (title, skills) values ('Software Systems Engineer','Innsolate, MagicDraw');
INSERT INTO jobs (title, skills) values ('Systems Architect','Unicom, Serrata');
INSERT INTO jobs (title, skills) values ('Systems Programmer','NetBeans, Python');
INSERT INTO jobs (title, skills) values ('Systems Software Designer','MATLAB, ZW3D, CATIA');
INSERT INTO jobs (title, skills) values ('Systems Software Specialist','Asana, JiRA');
INSERT INTO jobs (title, skills) values ('Web Content Developer','ColorZilla, Notepad++, AngularJS, Sublime Text');
INSERT INTO jobs (title, skills) values ('Web Designer','Dreamweaver, Photoshop');
INSERT INTO jobs (title, skills) values ('Web Developer','HTML, CSS');

/* Insert entries into employees table */

INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vincent','Myers',1,'VinMyers@gmail.com','vi762111');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dainton','Thompson',2,'DaiThompson@gmail.com','da609080');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brooke','Scott',3,'BroScott@gmail.com','br790562');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexander','Barnes',4,'AleBarnes@gmail.com','al720595');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jasmine','Smith',5,'JasSmith@gmail.com','ja262817');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Natalie','Bennett',6,'NatBennett@gmail.com','na656352');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adele','Jones',7,'AdeJones@gmail.com','ad781056');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dale','Mason',8,'DalMason@gmail.com','da701229');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adrian','Phillips',9,'AdrPhillips@gmail.com','ad726048');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Holmes',10,'CheHolmes@gmail.com','ch212830');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Deanna','Baker',11,'DeaBaker@gmail.com','de563317');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Wilson','Barnes',12,'WilBarnes@gmail.com','wi228970');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lenny','Mason',13,'LenMason@gmail.com','le373943');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Robert','Lloyd',14,'RobLloyd@gmail.com','ro266976');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vanessa','Tucker',15,'VanTucker@gmail.com','va702687');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ted','Anderson',16,'TedAnderson@gmail.com','te230174');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adam','Carter',17,'AdaCarter@gmail.com','ad777104');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Arianna','West',18,'AriWest@gmail.com','ar760644');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Annabella','Crawford',19,'AnnCrawford@gmail.com','an291697');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jasmine','Stewart',20,'JasStewart@gmail.com','ja334892');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Valeria','Edwards',21,'ValEdwards@gmail.com','va732885');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexander','Warren',22,'AleWarren@gmail.com','al516059');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abigail','Cunningham',23,'AbiCunningham@gmail.com','ab747177');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lucy','Harrison',24,'LucHarrison@gmail.com','lu747288');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('April','Baker',25,'AprBaker@gmail.com','ap133348');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Marcus','Harrison',26,'MarHarrison@gmail.com','ma813825');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chelsea','Perkins',27,'ChePerkins@gmail.com','ch828482');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Myra','Mitchell',28,'MyrMitchell@gmail.com','my667319');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aston','Brown',29,'AstBrown@gmail.com','as654242');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Hailey','Crawford',30,'HaiCrawford@gmail.com','ha121792');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rubie','Howard',31,'RubHoward@gmail.com','ru161093');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Myra','Cameron',1,'MyrCameron@gmail.com','my501427');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Carina','Campbell',2,'CarCampbell@gmail.com','ca242134');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daisy','Wells',3,'DaiWells@gmail.com','da944336');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Julian','Evans',4,'JulEvans@gmail.com','ju738177');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vivian','Tucker',5,'VivTucker@gmail.com','vi699931');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brooke','Richards',6,'BroRichards@gmail.com','br956413');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Hailey','Murray',7,'HaiMurray@gmail.com','ha600816');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Miranda','Elliott',8,'MirElliott@gmail.com','mi907889');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Julia','Bailey',9,'JulBailey@gmail.com','ju493052');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sarah','Campbell',10,'SarCampbell@gmail.com','sa925224');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Marcus','Campbell',11,'MarCampbell@gmail.com','ma565215');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tara','Andrews',12,'TarAndrews@gmail.com','ta326146');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Frederick','Perkins',13,'FrePerkins@gmail.com','fr132069');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Clark','Moore',14,'ClaMoore@gmail.com','cl501259');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Camila','Fowler',15,'CamFowler@gmail.com','ca881283');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daryl','Adams',16,'DarAdams@gmail.com','da810788');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sophia','Ferguson',17,'SopFerguson@gmail.com','so546466');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('April','Alexander',18,'AprAlexander@gmail.com','ap571508');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amber','Robinson',19,'AmbRobinson@gmail.com','am301075');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Victoria','Montgomery',20,'VicMontgomery@gmail.com','vi973526');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lana','Mason',21,'LanMason@gmail.com','la405309');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sofia','Perkins',22,'SofPerkins@gmail.com','so408724');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alissa','Cameron',23,'AliCameron@gmail.com','al552273');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lenny','Brown',24,'LenBrown@gmail.com','le669029');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Camila','Hawkins',25,'CamHawkins@gmail.com','ca175419');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Fenton','West',26,'FenWest@gmail.com','fe621618');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ryan','Tucker',27,'RyaTucker@gmail.com','ry664392');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Arianna','Harper',28,'AriHarper@gmail.com','ar746254');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Eleanor','Gibson',29,'EleGibson@gmail.com','el241524');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Martin','Barnes',30,'MarBarnes@gmail.com','ma758597');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jared','Barrett',31,'JarBarrett@gmail.com','ja892471');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Madaline','Perkins',1,'MadPerkins@gmail.com','ma971143');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Penelope','Thompson',2,'PenThompson@gmail.com','pe706536');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jared','Clark',3,'JarClark@gmail.com','ja841818');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rosie','Cameron',4,'RosCameron@gmail.com','ro381162');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Caroline','Anderson',5,'CarAnderson@gmail.com','ca485075');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elise','Dixon',6,'EliDixon@gmail.com','el237666');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Savana','Moore',7,'SavMoore@gmail.com','sa217774');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Madaline','Payne',8,'MadPayne@gmail.com','ma926389');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Olivia','Murray',9,'OliMurray@gmail.com','ol287698');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Miller',10,'CheMiller@gmail.com','ch280044');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paul','Allen',11,'PauAllen@gmail.com','pa782694');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rebecca','Alexander',12,'RebAlexander@gmail.com','re320737');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sophia','Miller',13,'SopMiller@gmail.com','so287352');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Max','Kelly',14,'MaxKelly@gmail.com','ma345788');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sydney','Kelley',15,'SydKelley@gmail.com','sy562691');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Miranda','Murphy',16,'MirMurphy@gmail.com','mi561489');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Emma','Fowler',17,'EmmFowler@gmail.com','em659889');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('John','Ross',18,'JohRoss@gmail.com','jo941599');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lilianna','Moore',19,'LilMoore@gmail.com','li908721');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Victoria','Spencer',20,'VicSpencer@gmail.com','vi391281');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Bruce','Cooper',21,'BruCooper@gmail.com','br956965');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alberta','Williams',22,'AlbWilliams@gmail.com','al412924');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adele','Craig',23,'AdeCraig@gmail.com','ad525851');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sophia','Cole',24,'SopCole@gmail.com','so271062');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ned','Allen',25,'NedAllen@gmail.com','ne568939');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elian','Spencer',26,'EliSpencer@gmail.com','el139604');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sofia','Howard',27,'SofHoward@gmail.com','so294183');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Madaline','Barrett',28,'MadBarrett@gmail.com','ma216455');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('James','Murray',29,'JamMurray@gmail.com','ja184820');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicole','Richards',30,'NicRichards@gmail.com','ni408155');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexia','Perkins',31,'AlePerkins@gmail.com','al657222');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Myra','Morrison',1,'MyrMorrison@gmail.com','my883701');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Edward','Perkins',2,'EdwPerkins@gmail.com','ed730573');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Walter','Reed',3,'WalReed@gmail.com','wa275528');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sabrina','Campbell',4,'SabCampbell@gmail.com','sa860442');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abigail','Chapman',5,'AbiChapman@gmail.com','ab735949');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ned','Williams',6,'NedWilliams@gmail.com','ne247201');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tess','Ryan',7,'TesRyan@gmail.com','te563324');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lucia','Ferguson',8,'LucFerguson@gmail.com','lu913562');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Eddy','Mitchell',9,'EddMitchell@gmail.com','ed995657');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Richard','Williams',10,'RicWilliams@gmail.com','ri852399');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kellan','Reed',11,'KelReed@gmail.com','ke561712');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Brooks',12,'CheBrooks@gmail.com','ch714423');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elian','Armstrong',13,'EliArmstrong@gmail.com','el690334');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Natalie','Morgan',14,'NatMorgan@gmail.com','na816141');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paige','Crawford',15,'PaiCrawford@gmail.com','pa412950');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amy','Cooper',16,'AmyCooper@gmail.com','am879781');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Leonardo','Allen',17,'LeoAllen@gmail.com','le785985');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Spike','Carter',18,'SpiCarter@gmail.com','sp283986');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Max','Brooks',19,'MaxBrooks@gmail.com','ma727358');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sofia','Higgins',20,'SofHiggins@gmail.com','so983301');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paige','Ellis',21,'PaiEllis@gmail.com','pa815387');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicholas','Armstrong',22,'NicArmstrong@gmail.com','ni522766');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Caroline','Hill',23,'CarHill@gmail.com','ca914256');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Penelope','Hamilton',24,'PenHamilton@gmail.com','pe665654');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tyler','Taylor',25,'TylTaylor@gmail.com','ty786638');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Luke','Ferguson',26,'LukFerguson@gmail.com','lu224636');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lucia','Taylor',27,'LucTaylor@gmail.com','lu284140');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('George','Morgan',28,'GeoMorgan@gmail.com','ge378170');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elise','Barnes',29,'EliBarnes@gmail.com','el125906');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Olivia','Andrews',30,'OliAndrews@gmail.com','ol419445');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Mary','Johnston',31,'MarJohnston@gmail.com','ma613857');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Andrew','Douglas',1,'AndDouglas@gmail.com','an607040');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexia','Carter',2,'AleCarter@gmail.com','al431778');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aston','Wilson',3,'AstWilson@gmail.com','as356487');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Samantha','Chapman',4,'SamChapman@gmail.com','sa191284');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vanessa','Ross',5,'VanRoss@gmail.com','va741449');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Samantha','Stewart',6,'SamStewart@gmail.com','sa824077');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Stuart','West',7,'StuWest@gmail.com','st427994');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dainton','Perry',8,'DaiPerry@gmail.com','da137035');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adrian','Carroll',9,'AdrCarroll@gmail.com','ad800658');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Oscar','Martin',10,'OscMartin@gmail.com','os781419');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adele','Howard',11,'AdeHoward@gmail.com','ad565671');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Heather','Allen',12,'HeaAllen@gmail.com','he519651');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sawyer','Kelley',13,'SawKelley@gmail.com','sa137963');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Gibson',14,'CheGibson@gmail.com','ch931904');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sam','Miller',15,'SamMiller@gmail.com','sa649805');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jenna','Hawkins',16,'JenHawkins@gmail.com','je938965');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Gianna','Perkins',17,'GiaPerkins@gmail.com','gi485439');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adrianna','Harris',18,'AdrHarris@gmail.com','ad595947');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dainton','Johnson',19,'DaiJohnson@gmail.com','da653408');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('George','Ryan',20,'GeoRyan@gmail.com','ge567171');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kevin','Robinson',21,'KevRobinson@gmail.com','ke801198');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Arnold','Grant',22,'ArnGrant@gmail.com','ar976258');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Eddy','Murphy',23,'EddMurphy@gmail.com','ed719167');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Roland','Wells',24,'RolWells@gmail.com','ro974531');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Melissa','Anderson',25,'MelAnderson@gmail.com','me625043');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alfred','Thompson',26,'AlfThompson@gmail.com','al338681');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tiana','Spencer',27,'TiaSpencer@gmail.com','ti152050');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Albert','West',28,'AlbWest@gmail.com','al375142');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chester','Harris',29,'CheHarris@gmail.com','ch375159');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Miranda','Hamilton',30,'MirHamilton@gmail.com','mi682497');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Victoria','Warren',31,'VicWarren@gmail.com','vi370253');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lucy','Harris',1,'LucHarris@gmail.com','lu170523');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Antony','Anderson',2,'AntAnderson@gmail.com','an291436');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Miranda','Turner',3,'MirTurner@gmail.com','mi233179');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dale','Murray',4,'DalMurray@gmail.com','da477873');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Robert','Gibson',5,'RobGibson@gmail.com','ro277507');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Valeria','Myers',6,'ValMyers@gmail.com','va388881');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Myra','Morris',7,'MyrMorris@gmail.com','my511745');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Richard','Stevens',8,'RicStevens@gmail.com','ri130716');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cadie','Campbell',9,'CadCampbell@gmail.com','ca601849');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vincent','Kelly',10,'VinKelly@gmail.com','vi112268');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sarah','Wilson',11,'SarWilson@gmail.com','sa574224');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alberta','Phillips',12,'AlbPhillips@gmail.com','al572116');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ted','Barnes',13,'TedBarnes@gmail.com','te669655');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Michael','Stevens',14,'MicStevens@gmail.com','mi565358');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Clark','Wright',15,'ClaWright@gmail.com','cl437716');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Stuart','Mason',16,'StuMason@gmail.com','st241866');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dale','Hamilton',17,'DalHamilton@gmail.com','da736338');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vivian','Richards',18,'VivRichards@gmail.com','vi638795');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amelia','Payne',19,'AmePayne@gmail.com','am709051');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Honey','Bennett',20,'HonBennett@gmail.com','ho562911');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amanda','Richards',21,'AmaRichards@gmail.com','am846572');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rubie','Farrell',22,'RubFarrell@gmail.com','ru214215');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Anna','Cole',23,'AnnCole@gmail.com','an299338');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Joyce','Phillips',24,'JoyPhillips@gmail.com','jo264865');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jasmine','Morrison',25,'JasMorrison@gmail.com','ja132171');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Carina','Wright',26,'CarWright@gmail.com','ca932840');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alen','Nelson',27,'AleNelson@gmail.com','al556223');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chloe','Johnston',28,'ChlJohnston@gmail.com','ch261922');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexander','Murphy',29,'AleMurphy@gmail.com','al834302');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Anna','Martin',30,'AnnMartin@gmail.com','an980231');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicole','Stevens',31,'NicStevens@gmail.com','ni839272');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jasmine','Thompson',1,'JasThompson@gmail.com','ja586741');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adison','Hunt',2,'AdiHunt@gmail.com','ad393301');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Garry','Farrell',3,'GarFarrell@gmail.com','ga632415');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Briony','Barnes',4,'BriBarnes@gmail.com','br779036');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sarah','Cole',5,'SarCole@gmail.com','sa918970');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicholas','Morrison',6,'NicMorrison@gmail.com','ni480861');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Edward','Ryan',7,'EdwRyan@gmail.com','ed568478');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aldus','Fowler',8,'AldFowler@gmail.com','al279986');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ryan','Crawford',9,'RyaCrawford@gmail.com','ry664614');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Evelyn','Grant',10,'EveGrant@gmail.com','ev556038');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jasmine','Cole',11,'JasCole@gmail.com','ja571465');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Freddie','Harrison',12,'FreHarrison@gmail.com','fr638565');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Arianna','Mitchell',13,'AriMitchell@gmail.com','ar957966');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Julia','Barnes',14,'JulBarnes@gmail.com','ju351391');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rubie','Martin',15,'RubMartin@gmail.com','ru568328');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Charlotte','Craig',16,'ChaCraig@gmail.com','ch562533');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abraham','Mason',17,'AbrMason@gmail.com','ab509301');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jordan','Murray',18,'JorMurray@gmail.com','jo802700');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Haris','Reed',19,'HarReed@gmail.com','ha560800');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dainton','Murray',20,'DaiMurray@gmail.com','da778268');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Walter','Harrison',21,'WalHarrison@gmail.com','wa385814');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alford','West',22,'AlfWest@gmail.com','al868999');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elian','Alexander',23,'EliAlexander@gmail.com','el619836');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vivian','Rogers',24,'VivRogers@gmail.com','vi418034');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Miller','Ryan',25,'MilRyan@gmail.com','mi462391');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amanda','Riley',26,'AmaRiley@gmail.com','am225179');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Justin','Myers',27,'JusMyers@gmail.com','ju282915');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alen','Allen',28,'AleAllen@gmail.com','al776791');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('James','Stevens',29,'JamStevens@gmail.com','ja666392');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Samantha','Reed',30,'SamReed@gmail.com','sa526802');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rebecca','Thompson',31,'RebThompson@gmail.com','re930133');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jared','Chapman',1,'JarChapman@gmail.com','ja660613');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Penelope','Brooks',2,'PenBrooks@gmail.com','pe416856');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Reid','Ferguson',3,'ReiFerguson@gmail.com','re455452');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Michael','Dixon',4,'MicDixon@gmail.com','mi717337');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Garry','Reed',5,'GarReed@gmail.com','ga704450');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Edward','Perkins',6,'EdwPerkins@gmail.com','ed490421');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ned','Parker',7,'NedParker@gmail.com','ne972782');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brad','Allen',8,'BraAllen@gmail.com','br815399');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicole','Barrett',9,'NicBarrett@gmail.com','ni958047');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lenny','Rogers',10,'LenRogers@gmail.com','le145492');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lily','Russell',11,'LilRussell@gmail.com','li569015');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rubie','Murphy',12,'RubMurphy@gmail.com','ru149923');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lily','Montgomery',13,'LilMontgomery@gmail.com','li238319');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tiana','Thomas',14,'TiaThomas@gmail.com','ti688286');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Naomi','Thompson',15,'NaoThompson@gmail.com','na243450');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Isabella','Warren',16,'IsaWarren@gmail.com','is359433');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alan','Alexander',17,'AlaAlexander@gmail.com','al999641');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ashton','Richardson',18,'AshRichardson@gmail.com','as855738');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chelsea','Murray',19,'CheMurray@gmail.com','ch399649');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jenna','Adams',20,'JenAdams@gmail.com','je626589');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jacob','Gray',21,'JacGray@gmail.com','ja255456');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lucas','Smith',22,'LucSmith@gmail.com','lu293901');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Penelope','Payne',23,'PenPayne@gmail.com','pe360583');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tiana','Smith',24,'TiaSmith@gmail.com','ti823219');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chelsea','Mason',25,'CheMason@gmail.com','ch707204');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Blake','Adams',26,'BlaAdams@gmail.com','bl865026');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aiden','Farrell',27,'AidFarrell@gmail.com','ai463169');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Charlotte','Fowler',28,'ChaFowler@gmail.com','ch805741');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ryan','Edwards',29,'RyaEdwards@gmail.com','ry769088');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Gianna','Anderson',30,'GiaAnderson@gmail.com','gi234231');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Reid','Davis',31,'ReiDavis@gmail.com','re747283');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicole','Phillips',1,'NicPhillips@gmail.com','ni740149');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Watson',2,'CheWatson@gmail.com','ch407385');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Richard','Bennett',3,'RicBennett@gmail.com','ri751951');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kristian','Elliott',4,'KriElliott@gmail.com','kr111213');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abraham','Douglas',5,'AbrDouglas@gmail.com','ab551713');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Isabella','Hawkins',6,'IsaHawkins@gmail.com','is690430');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sarah','Perkins',7,'SarPerkins@gmail.com','sa265728');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Walter','Payne',8,'WalPayne@gmail.com','wa464485');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('James','Murphy',9,'JamMurphy@gmail.com','ja859148');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Luke','Brown',10,'LukBrown@gmail.com','lu848071');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daryl','Stewart',11,'DarStewart@gmail.com','da274399');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Anna','Riley',12,'AnnRiley@gmail.com','an376464');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Valeria','Morrison',13,'ValMorrison@gmail.com','va994367');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Camila','Lloyd',14,'CamLloyd@gmail.com','ca696117');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Cherry','Cooper',15,'CheCooper@gmail.com','ch141193');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alan','Roberts',16,'AlaRoberts@gmail.com','al364538');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Frederick','Casey',17,'FreCasey@gmail.com','fr481221');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daryl','Richardson',18,'DarRichardson@gmail.com','da660200');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicholas','Bennett',19,'NicBennett@gmail.com','ni390052');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Myra','Thompson',20,'MyrThompson@gmail.com','my681235');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Maria','Higgins',21,'MarHiggins@gmail.com','ma240036');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Maddie','Cunningham',22,'MadCunningham@gmail.com','ma174931');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Michael','Miller',23,'MicMiller@gmail.com','mi247801');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chloe','Watson',24,'ChlWatson@gmail.com','ch908667');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Arianna','Gray',25,'AriGray@gmail.com','ar740380');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('April','Craig',26,'AprCraig@gmail.com','ap830851');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ashton','Douglas',27,'AshDouglas@gmail.com','as729359');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daryl','Clark',28,'DarClark@gmail.com','da131070');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amy','Carroll',29,'AmyCarroll@gmail.com','am959701');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lilianna','Martin',30,'LilMartin@gmail.com','li811099');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Nicole','Morrison',31,'NicMorrison@gmail.com','ni434542');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Edith','Cameron',1,'EdiCameron@gmail.com','ed592991');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Luke','Tucker',2,'LukTucker@gmail.com','lu542887');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Maximilian','Elliott',3,'MaxElliott@gmail.com','ma344506');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kimberly','Carter',4,'KimCarter@gmail.com','ki998381');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Owen','Kelley',5,'OweKelley@gmail.com','ow550740');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Reid','Armstrong',6,'ReiArmstrong@gmail.com','re882368');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Mary','Brooks',7,'MarBrooks@gmail.com','ma170137');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Mary','Phillips',8,'MarPhillips@gmail.com','ma335639');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Deanna','Fowler',9,'DeaFowler@gmail.com','de168654');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Camila','Myers',10,'CamMyers@gmail.com','ca804003');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Michelle','Gray',11,'MicGray@gmail.com','mi856922');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ryan','Elliott',12,'RyaElliott@gmail.com','ry784890');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('William','Gibson',13,'WilGibson@gmail.com','wi811506');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Anna','Montgomery',14,'AnnMontgomery@gmail.com','an161061');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Emily','Turner',15,'EmiTurner@gmail.com','em117429');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Darcy','Hill',16,'DarHill@gmail.com','da233846');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Connie','Allen',17,'ConAllen@gmail.com','co344754');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tony','Elliott',18,'TonElliott@gmail.com','to727484');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alen','Evans',19,'AleEvans@gmail.com','al460182');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Elise','Foster',20,'EliFoster@gmail.com','el666839');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Daryl','Hunt',21,'DarHunt@gmail.com','da901475');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Oliver','Smith',22,'OliSmith@gmail.com','ol490166');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alexander','Evans',23,'AleEvans@gmail.com','al945808');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Catherine','Craig',24,'CatCraig@gmail.com','ca634925');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abigail','Farrell',25,'AbiFarrell@gmail.com','ab286444');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kirsten','Hawkins',26,'KirHawkins@gmail.com','ki276623');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Charlotte','Clark',27,'ChaClark@gmail.com','ch715402');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('David','Montgomery',28,'DavMontgomery@gmail.com','da894885');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Grace','Phillips',29,'GraPhillips@gmail.com','gr752975');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lenny','Ryan',30,'LenRyan@gmail.com','le676220');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Robert','Bailey',31,'RobBailey@gmail.com','ro147824');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brooke','Hall',1,'BroHall@gmail.com','br138557');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Agata','Moore',2,'AgaMoore@gmail.com','ag573415');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Briony','Baker',3,'BriBaker@gmail.com','br215568');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alford','Chapman',4,'AlfChapman@gmail.com','al761010');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Grace','Rogers',5,'GraRogers@gmail.com','gr744223');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kellan','Carter',6,'KelCarter@gmail.com','ke724289');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Walter','Henderson',7,'WalHenderson@gmail.com','wa371564');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Joyce','Gray',8,'JoyGray@gmail.com','jo841774');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Michael','Hall',9,'MicHall@gmail.com','mi605357');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dexter','Walker',10,'DexWalker@gmail.com','de501081');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jessica','Wells',11,'JesWells@gmail.com','je305963');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tara','Evans',12,'TarEvans@gmail.com','ta140926');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Fiona','Andrews',13,'FioAndrews@gmail.com','fi784551');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jared','Perry',14,'JarPerry@gmail.com','ja916666');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ted','Nelson',15,'TedNelson@gmail.com','te767080');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amy','Ross',16,'AmyRoss@gmail.com','am855150');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jessica','Scott',17,'JesScott@gmail.com','je954242');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Victor','Cole',18,'VicCole@gmail.com','vi980509');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Owen','Ryan',19,'OweRyan@gmail.com','ow707649');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sam','Hill',20,'SamHill@gmail.com','sa644112');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ted','Gray',21,'TedGray@gmail.com','te776625');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jacob','Harrison',22,'JacHarrison@gmail.com','ja337957');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sofia','Evans',23,'SofEvans@gmail.com','so209474');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Byron','Smith',24,'ByrSmith@gmail.com','by587718');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('James','Montgomery',25,'JamMontgomery@gmail.com','ja330845');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adele','Ryan',26,'AdeRyan@gmail.com','ad124753');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Fenton','Cameron',27,'FenCameron@gmail.com','fe165932');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Sydney','Holmes',28,'SydHolmes@gmail.com','sy460959');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Vanessa','Dixon',29,'VanDixon@gmail.com','va708763');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Antony','Gibson',30,'AntGibson@gmail.com','an405537');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Martin','Kelley',31,'MarKelley@gmail.com','ma884679');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Isabella','Baker',1,'IsaBaker@gmail.com','is171790');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dale','Warren',2,'DalWarren@gmail.com','da875398');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tiana','Kelley',3,'TiaKelley@gmail.com','ti709349');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alford','Roberts',4,'AlfRoberts@gmail.com','al242482');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aldus','Kelly',5,'AldKelly@gmail.com','al991031');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dexter','Brown',6,'DexBrown@gmail.com','de591988');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Marcus','Dixon',7,'MarDixon@gmail.com','ma847889');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Abraham','Morrison',8,'AbrMorrison@gmail.com','ab181836');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Agata','Higgins',9,'AgaHiggins@gmail.com','ag610103');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Marcus','Cooper',10,'MarCooper@gmail.com','ma725083');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dale','Hamilton',11,'DalHamilton@gmail.com','da789015');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Albert','Riley',12,'AlbRiley@gmail.com','al918938');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Freddie','Johnson',13,'FreJohnson@gmail.com','fr970788');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Alford','Turner',14,'AlfTurner@gmail.com','al157650');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Edwin','Myers',15,'EdwMyers@gmail.com','ed389710');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Chelsea','Wells',16,'CheWells@gmail.com','ch114502');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aldus','Fowler',17,'AldFowler@gmail.com','al421111');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Eric','Nelson',18,'EriNelson@gmail.com','er273794');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Amanda','Johnson',19,'AmaJohnson@gmail.com','am845511');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Charlie','Dixon',20,'ChaDixon@gmail.com','ch473488');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adrian','Henderson',21,'AdrHenderson@gmail.com','ad620605');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tony','Wells',22,'TonWells@gmail.com','to972481');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brad','Henderson',23,'BraHenderson@gmail.com','br700592');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Brooke','Morris',24,'BroMorris@gmail.com','br449269');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Richard','Johnston',25,'RicJohnston@gmail.com','ri823782');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Tiana','Jones',26,'TiaJones@gmail.com','ti334692');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Darcy','Casey',27,'DarCasey@gmail.com','da555584');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Stuart','Williams',28,'StuWilliams@gmail.com','st230892');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Rebecca','Myers',29,'RebMyers@gmail.com','re232670');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Frederick','Crawford',30,'FreCrawford@gmail.com','fr794282');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('William','Craig',31,'WilCraig@gmail.com','wi214353');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Briony','Holmes',1,'BriHolmes@gmail.com','br114386');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paige','Richardson',2,'PaiRichardson@gmail.com','pa360192');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Belinda','Martin',3,'BelMartin@gmail.com','be875828');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('John','Stevens',4,'JohStevens@gmail.com','jo725157');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Audrey','Warren',5,'AudWarren@gmail.com','au128454');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Frederick','Watson',6,'FreWatson@gmail.com','fr643631');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adrianna','Russell',7,'AdrRussell@gmail.com','ad545613');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Walter','Hamilton',8,'WalHamilton@gmail.com','wa591682');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Aida','Ferguson',9,'AidFerguson@gmail.com','ai203549');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Oscar','Riley',10,'OscRiley@gmail.com','os198478');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paul','Alexander',11,'PauAlexander@gmail.com','pa644616');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Kate','Carroll',12,'KatCarroll@gmail.com','ka947379');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Dexter','Edwards',13,'DexEdwards@gmail.com','de141759');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Eddy','Miller',14,'EddMiller@gmail.com','ed299574');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adele','Bailey',15,'AdeBailey@gmail.com','ad236258');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Paul','Hunt',16,'PauHunt@gmail.com','pa721842');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('William','Armstrong',17,'WilArmstrong@gmail.com','wi266245');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jacob','Reed',18,'JacReed@gmail.com','ja761516');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Jenna','Smith',19,'JenSmith@gmail.com','je282395');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Hailey','Wells',20,'HaiWells@gmail.com','ha663577');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Reid','Mitchell',21,'ReiMitchell@gmail.com','re721674');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adam','Montgomery',22,'AdaMontgomery@gmail.com','ad576659');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Victoria','Perkins',23,'VicPerkins@gmail.com','vi151069');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Ellia','Rogers',24,'EllRogers@gmail.com','el758445');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Joyce','West',25,'JoyWest@gmail.com','jo317691');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Adison','Mason',26,'AdiMason@gmail.com','ad587541');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Lana','Higgins',27,'LanHiggins@gmail.com','la619727');
INSERT INTO employees (firstName,lastName,job_id, email, pwd) values ('Mary ','Obrien',9,'MarObrien@gmail.com','ma296432');

/* Insert entries into jobsdata table */

INSERT INTO jobads (job_id, emp_id, status) values (1,1,0);
INSERT INTO jobads (job_id, emp_id, status) values (2,2,0);
INSERT INTO jobads (job_id, emp_id, status) values (3,2,0);
INSERT INTO jobads (job_id, emp_id, status) values (4,1,0);
INSERT INTO jobads (job_id, emp_id, status) values (5,35,1);
INSERT INTO jobads (job_id, emp_id, status) values (6,1,1);
INSERT INTO jobads (job_id, emp_id, status) values (7,34,1);
INSERT INTO jobads (job_id, emp_id, status) values (8,1,1);
INSERT INTO jobads (job_id, emp_id, status) values (9,1,0);
INSERT INTO jobads (job_id, emp_id, status) values (10,2,0);
INSERT INTO jobads (job_id, emp_id, status) values (11,3,0);
INSERT INTO jobads (job_id, emp_id, status) values (12,3,0);
INSERT INTO jobads (job_id, emp_id, status) values (13,4,1);
INSERT INTO jobads (job_id, emp_id, status) values (14,6,1);
INSERT INTO jobads (job_id, emp_id, status) values (15,7,0);
INSERT INTO jobads (job_id, emp_id, status) values (16,7,0);
INSERT INTO jobads (job_id, emp_id, status) values (17,8,0);
INSERT INTO jobads (job_id, emp_id, status) values (18,8,0);
INSERT INTO jobads (job_id, emp_id, status) values (19,8,0);
INSERT INTO jobads (job_id, emp_id, status) values (20,8,0);
INSERT INTO jobads (job_id, emp_id, status) values (21,4,0);
INSERT INTO jobads (job_id, emp_id, status) values (22,9,0);
INSERT INTO jobads (job_id, emp_id, status) values (23,1,0);
INSERT INTO jobads (job_id, emp_id, status) values (24,2,0);
INSERT INTO jobads (job_id, emp_id, status) values (25,3,0);
INSERT INTO jobads (job_id, emp_id, status) values (26,4,0);
INSERT INTO jobads (job_id, emp_id, status) values (27,23,1);
INSERT INTO jobads (job_id, emp_id, status) values (28,34,1);
INSERT INTO jobads (job_id, emp_id, status) values (29,25,1);
INSERT INTO jobads (job_id, emp_id, status) values (30,27,1);
INSERT INTO jobads (job_id, emp_id, status) values (31,26,1);